2020-03-04 17:48:02,906 ERROR 12232 [-/::1/-/7ms GET /login] nodejs.TypeError: Cannot read property 'login' of undefined
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:11:50)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 12232
hostname: shenw

2020-03-04 17:49:57,692 ERROR 20808 [-/::1/-/9ms GET /login] nodejs.TypeError: Cannot read property 'login' of undefined
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:11:50)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 20808
hostname: shenw

2020-03-04 17:52:11,864 ERROR 4008 [-/::1/-/4ms GET /login] nodejs.ReferenceError: admin is not defined
    at AdminLoginService.login (F:\huaserver\server\app\service\adminLogin.js:10:38)
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:11:50)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)

pid: 4008
hostname: shenw

2020-03-04 17:53:31,738 ERROR 8272 [-/::1/-/5ms GET /login] nodejs.ReferenceError: admin is not defined
    at AdminLoginService.login (F:\huaserver\server\app\service\adminLogin.js:10:41)
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:11:50)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)

pid: 8272
hostname: shenw

2020-03-04 21:00:42,555 ERROR 3988 [-/::1/-/4ms GET /login] nodejs.ReferenceError: username is not defined
    at AdminLoginService.login (F:\huaserver\server\app\service\adminLogin.js:11:7)
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:11:50)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)

pid: 3988
hostname: shenw

2020-03-04 21:02:15,495 ERROR 3988 [-/::1/-/1ms GET /login] nodejs.ReferenceError: username is not defined
    at AdminLoginService.login (F:\huaserver\server\app\service\adminLogin.js:11:7)
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:11:50)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)

pid: 3988
hostname: shenw

2020-03-04 21:26:30,991 ERROR 4984 [-/::1/-/31ms POST /login] nodejs.TypeError: service.adminLogin.log is not a function
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:13:43)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 4984
hostname: shenw

2020-03-04 21:29:27,140 ERROR 22208 [-/::1/-/40ms POST /login] nodejs.TypeError: service.adminLogin.log is not a function
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:13:43)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 22208
hostname: shenw

2020-03-04 21:30:32,196 ERROR 22208 [-/::1/-/4ms POST /login] nodejs.TypeError: service.adminLogin.log is not a function
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:13:43)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 22208
hostname: shenw

2020-03-04 21:30:58,825 ERROR 22208 [-/::1/-/4ms POST /login] nodejs.TypeError: service.adminLogin.log is not a function
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:13:43)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 22208
hostname: shenw

2020-03-04 21:31:22,761 ERROR 22208 [-/::1/-/3ms POST /login] nodejs.TypeError: service.adminLogin.log is not a function
    at LoginController.adminLogin (F:\huaserver\server\app\controller\login.js:13:43)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 22208
hostname: shenw

2020-03-05 10:32:18,527 ERROR 1824 [-/::1/-/9ms GET /adminLogin/loginname?loginid=1] nodejs.ReferenceError: loginData is not defined
    at AdminLoginController.loginname (F:\huaserver\server\app\controller\adminLogin.js:41:53)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 1824
hostname: shenw

2020-03-05 10:34:33,199 ERROR 18376 [-/::1/-/12ms GET /adminLogin/loginname?loginid=1] nodejs.ReferenceError: loginid is not defined
    at AdminLoginController.loginname (F:\huaserver\server\app\controller\adminLogin.js:44:12)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 18376
hostname: shenw

2020-03-05 17:50:43,775 ERROR 17796 [-/::1/-/7ms GET /delinfo?index=0] nodejs.TypeError: service.delinfo.delinfo is not a function
    at DelinfoController.del (F:\huaserver\server\app\controller\delinfo.js:13:40)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17796
hostname: shenw

2020-03-05 18:34:31,665 ERROR 16712 [-/::1/-/72ms GET /delinfo?id=3] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: DELETE FROM `user` WHERE `id` = '3'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `user` WHERE `id` = '3'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16712
hostname: shenw

2020-03-06 08:22:32,777 ERROR 17060 [-/::1/-/6ms GET /adminedit] nodejs.TypeError: Cannot read property 'edit' of undefined
    at AdmineditController.edit (F:\huaserver\server\app\controller\adminedit.js:14:41)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17060
hostname: shenw

2020-03-06 08:24:16,004 ERROR 17744 [-/::1/-/7ms GET /adminedit] nodejs.TypeError: Cannot read property 'edit' of undefined
    at AdmineditController.edit (F:\huaserver\server\app\controller\adminedit.js:14:41)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17744
hostname: shenw

2020-03-06 08:25:07,209 ERROR 16608 [-/::1/-/7ms GET /adminedit] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `cid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `cid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `cid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `cid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 16608
hostname: shenw

2020-03-06 08:26:30,920 ERROR 16380 [-/::1/-/11ms GET /adminedit] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `cid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `cid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `cid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `cid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 16380
hostname: shenw

2020-03-06 08:27:36,349 ERROR 18180 [-/::1/-/10ms GET /adminedit] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `uid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 18180
hostname: shenw

2020-03-06 08:27:40,231 ERROR 18180 [-/::1/-/4ms GET /adminedit] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `uid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 18180
hostname: shenw

2020-03-06 08:30:16,227 ERROR 18208 [-/::1/-/10ms GET /adminedit] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `uid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 18208
hostname: shenw

2020-03-06 08:31:29,100 ERROR 15516 [-/::1/-/14ms GET /adminedit] nodejs.TypeError: val.toString is not a function
    at Object.escape [as __escape] (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:52:33)
    at Object.SqlString.escape (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\sqlstring.js:19:22)
    at Object.objectToValues (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:180:89)
    at Object.escape [as __escape] (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:54:26)
    at Object.SqlString.escape (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\sqlstring.js:19:22)
    at Object.format (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:100:19)
    at RDSClient.proto.format (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:43:20)
    at RDSClient.proto.update (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:170:10)
    at proto.update.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15516
hostname: shenw

2020-03-06 08:32:16,612 ERROR 15516 [-/::1/-/5ms GET /adminedit] nodejs.TypeError: val.toString is not a function
    at Object.escape [as __escape] (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:52:33)
    at Object.SqlString.escape (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\sqlstring.js:19:22)
    at Object.objectToValues (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:180:89)
    at Object.escape [as __escape] (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:54:26)
    at Object.SqlString.escape (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\sqlstring.js:19:22)
    at Object.format (F:\huaserver\server\node_modules\_sqlstring@2.3.1@sqlstring\lib\SqlString.js:100:19)
    at RDSClient.proto.format (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:43:20)
    at RDSClient.proto.update (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:170:10)
    at proto.update.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15516
hostname: shenw

2020-03-06 08:32:40,214 ERROR 18132 [-/::1/-/7ms GET /adminedit] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `uid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 18132
hostname: shenw

2020-03-06 08:34:33,419 ERROR 18132 [-/::1/-/7ms GET /adminedit?uid=1] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `uid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 18132
hostname: shenw

2020-03-06 08:34:56,759 ERROR 18132 [-/::1/-/8ms GET /adminedit?uid=1] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET  WHERE `uid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `user` SET  WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 18132
hostname: shenw

2020-03-06 08:35:29,486 ERROR 18132 [-/::1/-/5ms GET /adminedit?uid=1&uname=414&upasswd=044] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'upasswd' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `uname` = '414', `upasswd` = '044' WHERE `uid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'upasswd' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `uname` = '414', `upasswd` = '044' WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18132
hostname: shenw

2020-03-06 08:36:52,405 ERROR 10676 [-/::1/-/14ms GET /adminedit?uid=1&uname=414&upasswd=044] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column '0' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `0` = '1' WHERE `uid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '0' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `0` = '1' WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 10676
hostname: shenw

2020-03-06 08:39:59,381 ERROR 10676 [-/::1/-/5131ms GET /adminedit?uid=1&uname=414&upasswd=044] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column '0' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `0` = '1' WHERE `uid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '0' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `0` = '1' WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 10676
hostname: shenw

2020-03-06 08:39:59,396 ERROR 10676 [-/::1/-/3ms GET /adminedit?uid=1&uname=414&upasswd=044] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column '0' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `0` = '1' WHERE `uid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column '0' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `0` = '1' WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 10676
hostname: shenw

2020-03-06 08:40:04,899 ERROR 19696 [-/::1/-/10ms GET /adminedit?uid=1&uname=414&upasswd=044] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'upasswd' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `uname` = '414', `upasswd` = '044' WHERE `uid` = '1'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'upasswd' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `uname` = '414', `upasswd` = '044' WHERE `uid` = '1'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19696
hostname: shenw

2020-03-06 08:40:10,103 ERROR 19696 [-/::1/-/4ms GET /adminedit?uid=1&uname=414&upasswd=044] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'upasswd' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `uname` = '414', `upasswd` = '044' WHERE `uid` = '1'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'upasswd' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `uname` = '414', `upasswd` = '044' WHERE `uid` = '1'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19696
hostname: shenw

2020-03-06 10:32:14,448 ERROR 6736 [-/::1/-/3ms GET /getShop/delshop?id=2] nodejs.ReferenceError: sid is not defined
    at GetshopService.delshop (F:\huaserver\server\app\service\getshop.js:16:7)
    at GetshopController.delshop (F:\huaserver\server\app\controller\getshop.js:22:40)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6736
hostname: shenw

2020-03-06 10:34:30,814 ERROR 6736 [-/::1/-/11895ms GET /getShop/delshop?id=2] nodejs.ReferenceError: sid is not defined
    at GetshopService.delshop (F:\huaserver\server\app\service\getshop.js:16:7)
    at GetshopController.delshop (F:\huaserver\server\app\controller\getshop.js:22:40)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6736
hostname: shenw

2020-03-06 10:34:48,347 ERROR 16016 [-/::1/-/9ms GET /getShop/delshop?id=2] nodejs.ReferenceError: sid is not defined
    at GetshopService.delshop (F:\huaserver\server\app\service\getshop.js:16:7)
    at GetshopController.delshop (F:\huaserver\server\app\controller\getshop.js:22:40)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 16016
hostname: shenw

2020-03-06 10:35:24,476 ERROR 16016 [-/::1/-/5398ms GET /getShop/delshop?id=2] nodejs.ReferenceError: sid is not defined
    at GetshopService.delshop (F:\huaserver\server\app\service\getshop.js:16:7)
    at GetshopController.delshop (F:\huaserver\server\app\controller\getshop.js:22:40)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 16016
hostname: shenw

2020-03-06 10:35:44,166 ERROR 17428 [-/::1/-/11ms GET /getShop/delshop?id=1] nodejs.ReferenceError: sid is not defined
    at GetshopService.delshop (F:\huaserver\server\app\service\getshop.js:16:7)
    at GetshopController.delshop (F:\huaserver\server\app\controller\getshop.js:22:40)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17428
hostname: shenw

2020-03-06 10:36:26,359 ERROR 21224 [-/::1/-/13ms GET /getShop/delshop?id=2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: DELETE FROM `shop` WHERE `sid` = `id` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `shop` WHERE `sid` = `id` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 21224
hostname: shenw

2020-03-06 11:08:22,957 ERROR 15244 [-/::1/-/4ms GET /adminedit?name=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `user` SET `name` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `uid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `user` SET `name` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `uid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 15244
hostname: shenw

2020-03-06 11:14:56,031 ERROR 17484 [-/::1/-/8ms GET /getShop/updshop?name=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.TypeError: service.adminedit.updshop is not a function
    at GetshopController.updshop (F:\huaserver\server\app\controller\getshop.js:40:44)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 17484
hostname: shenw

2020-03-06 11:16:18,633 ERROR 16808 [-/::1/-/11ms GET /getShop/updshop?name=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `name` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `name` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:16:23,426 ERROR 16808 [-/::1/-/3ms GET /getShop/updshop?name=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `name` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `name` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:19:03,370 ERROR 16808 [-/::1/-/3ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:19:56,356 ERROR 16808 [-/::1/-/9024ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:19:56,382 ERROR 16808 [-/::1/-/7ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:19:56,396 ERROR 16808 [-/::1/-/5ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:19:56,408 ERROR 16808 [-/::1/-/7ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 16808
hostname: shenw

2020-03-06 11:20:46,019 ERROR 18320 [-/::1/-/11ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18320
hostname: shenw

2020-03-06 11:21:53,996 ERROR 18320 [-/::1/-/3ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18320
hostname: shenw

2020-03-06 11:23:37,216 ERROR 18320 [-/::1/-/4284ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18320
hostname: shenw

2020-03-06 11:24:43,167 ERROR 18320 [-/::1/-/3ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18320
hostname: shenw

2020-03-06 11:25:34,705 ERROR 18320 [-/::1/-/3ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18320
hostname: shenw

2020-03-06 11:27:23,986 ERROR 18320 [-/::1/-/2ms GET /getShop/updshop?id=2&sname=%E6%8C%82%E5%8F%B7%E8%B4%B9&simg=0&bfprice=1234&afprice=123&sinfo=%E5%B7%A5%E4%BC%9A%E7%BB%8F%E8%B4%B9] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `shop` SET `id` = '2', `sname` = '挂号费', `simg` = '0', `bfprice` = '1234', `afprice` = '123', `sinfo` = '工会经费' WHERE `sid` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18320
hostname: shenw

2020-03-06 13:40:18,216 ERROR 10152 [-/::1/-/6ms GET /getShop/updshop] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `sid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET  WHERE `sid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `sid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `shop` SET  WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 10152
hostname: shenw

2020-03-06 13:52:45,583 ERROR 10152 [-/::1/-/3ms GET /getShop/updshop] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `sid` IS NULL' at line 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `shop` SET  WHERE `sid` IS NULL
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `sid` IS NULL' at line 1"
sqlState: "42000"
index: 0
sql: "UPDATE `shop` SET  WHERE `sid` IS NULL"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 10152
hostname: shenw

2020-03-06 14:12:31,840 ERROR 15528 [-/::1/-/10ms GET /getShop/addshop?name=425&simg=452&bfprice=45&afprice=45&sinfo=45] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `shop`(`name`, `simg`, `bfprice`, `afprice`, `sinfo`) VALUES('425', '452', '45', '45', '45')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `shop`(`name`, `simg`, `bfprice`, `afprice`, `sinfo`) VALUES('425', '452', '45', '45', '45')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 15528
hostname: shenw

2020-03-06 14:29:41,588 ERROR 19596 [-/::1/-/12ms GET /getinfo/addadmin?uid=&uname=%E9%82%93&upwd=%E4%B8%8A%E7%9A%84] nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: '' for column 'uid' at row 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`uid`, `uname`, `upwd`) VALUES('', '邓', '上的')
code: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"
errno: 1366
sqlMessage: "Incorrect integer value: '' for column 'uid' at row 1"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`uid`, `uname`, `upwd`) VALUES('', '邓', '上的')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError"
pid: 19596
hostname: shenw

2020-03-06 14:29:42,592 ERROR 19596 [-/::1/-/3ms GET /getinfo/addadmin?uid=&uname=%E9%82%93&upwd=%E4%B8%8A%E7%9A%84] nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: '' for column 'uid' at row 1
    at Query.Sequence._packetToError (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Pool.query (F:\huaserver\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (F:\huaserver\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\huaserver\server\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at F:\huaserver\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`uid`, `uname`, `upwd`) VALUES('', '邓', '上的')
code: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"
errno: 1366
sqlMessage: "Incorrect integer value: '' for column 'uid' at row 1"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`uid`, `uname`, `upwd`) VALUES('', '邓', '上的')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError"
pid: 19596
hostname: shenw

2020-03-06 18:17:53,267 ERROR 2612 [-/::1/-/8ms POST /upload] nodejs.TypeError: Cannot read property '0' of undefined
    at UploadController.index (F:\huaserver\server\app\controller\upload.js:14:35)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 2612
hostname: shenw

2020-03-06 21:23:35,635 ERROR 5392 [-/::1/-/6ms POST /upload] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UploadController.index (F:\huaserver\server\app\controller\upload.js:16:66)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 5392
hostname: shenw

2020-03-06 21:25:00,605 ERROR 5392 [-/::1/-/13259ms POST /upload] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UploadController.index (F:\huaserver\server\app\controller\upload.js:16:66)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 5392
hostname: shenw

2020-03-06 21:25:00,665 ERROR 5392 [-/::1/-/2ms POST /upload] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UploadController.index (F:\huaserver\server\app\controller\upload.js:16:66)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 5392
hostname: shenw

2020-03-06 21:31:05,843 ERROR 5288 [-/::1/-/7448ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 5288
hostname: shenw

2020-03-06 21:32:08,815 ERROR 14792 [-/::1/-/19ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 14792
hostname: shenw

2020-03-06 21:35:32,821 ERROR 19688 [-/::1/-/14ms POST /uploads] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:66)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 19688
hostname: shenw

2020-03-06 21:46:03,505 ERROR 15212 [-/::1/-/19ms POST /uploads] nodejs.TypeError: Cannot read property 'filepath' of undefined
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:66)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15212
hostname: shenw

2020-03-06 21:47:06,103 ERROR 15944 [-/::1/-/15ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15944
hostname: shenw

2020-03-06 22:14:31,366 ERROR 15944 [-/::1/-/4521ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15944
hostname: shenw

2020-03-06 22:14:37,825 ERROR 15944 [-/::1/-/4ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15944
hostname: shenw

2020-03-06 22:15:24,162 ERROR 15944 [-/::1/-/4ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 15944
hostname: shenw

2020-03-06 22:21:49,440 ERROR 3732 [-/::1/-/29ms POST /uploads] nodejs.TypeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at UploadsController.index (F:\huaserver\server\app\controller\uploads.js:16:52)
    at Object.callFn (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\huaserver\server\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\huaserver\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\huaserver\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
code: "ERR_INVALID_ARG_TYPE"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 3732
hostname: shenw

